### PR TITLE
ocn: Enable call recording feature

### PR DESCRIPTION
**Pull request by iGeekl**
Change-Id: I1b4478b330b13cf5d0fe1ed0d40f43e4b3825f33

### CODE REVIEW

**Comment by Golv** [comment]
Enabled or disabled call recording function for some countries:
https://github.com/LineageOS/android_packages_apps_Dialer/blob/lineage-18.1/java/com/android/dialer/callrecord/res/xml/call_record_states.xml

**Comment by iGeekl** [comment]
Without this, no "Record call" button while calling, call recording can't be actived.

**Comment by iGeekl** [comment]
Mine is China version, it should be ok to record ,but no "Record call" button  at all , now my own builds works. Maybe you can test it in other version, thanks.

**Comment by iGeekl** [comment]
Besides, i think the problem "The main problem - there is no voice when calling." with Android Pie firmware , now can be resolved. The problem should be adsp blobs, need to be exacted from Android Pie firmware. I tried to update adsp blobs and corrected ro_build_fingerprint_prop with official  9.0's value.  Then i have already successfully maked severa calls while audio works.   You can take a try.

**Comment by Golv** [comment]
Very good!
Can you share correct ro_build_fingerprint_prop commit?

**Comment by iGeekl** [comment]
The  Android Pie's ADSP blobs must be used with Android Pie's DSP image , so the Android Oreo. Or still no audio while calling. ro_build_fingerprint_prop is not the reason.

**Comment by Golv** [comment]
I was sure that with Pie's ADSP blobs, there may be problems with no audio while calling, if the Oreo DSP image is installed.
In this case, need to install Pie DSP image patch.

**Comment by Golv** [comment]
In case of Pie's ADSP blobs all real LOS 18.1 and PE 11plus users will need to force Pie DSP image back or install it.

**Pull request closed without merging**
